version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.250.98.246
      KAFKA_ZOOKEEPER_CONNECT: 10.250.98.246:2181
      KAFKA_CREATE_TOPICS: "user.msg:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
