database:
  server: mongodb.dev
  port: 27017
  dbName: user_db

# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

logging:
  level: INFO

  appenders:
    - type: console